package edu.mit.csail.netmap;

/** All the events generated by the NetMap library. */
public interface NetMapListener {
  /**
   * Called when the Android-reported location changes.
   * 
   * {@link NetMap#location()} can be called to obtain the new location. This is
   * intended to help locate the user in the game world.
   */
  public void onLocation();
  
  /**
   * Called when the Android-reported battery state changes.
   * 
   * {@link NetMap#powerSource()} can be called to obtain the new battery
   * state. This is intended to help decide when measurement data should be
   * uploaded to the server.
   */
  public void onBattery();
  
  /**
   * Called when the Android-reported network connection type changes. 
   * 
   * {@link NetMap#networkState()} can be called to obtain the new network
   * connection type. This is intended to help decide when measurement data
   * should be uploaded to the server.
   */
  public void onNetwork();
}