package edu.mit.csail.netmap;

import edu.mit.csail.netmap.sensors.Location;

/** All the events generated by the NetMap library. */
public interface NetMapListener {
  /**
   * Called when the Android-reported location changes.
   * 
   * {@link Location#getJson(StringBuffer)} can be called to obtain information
   * about the new location.
   */
  public void onLocation();
}
