package edu.mit.csail.netmap.sensors;

/** All events generated by sensors. */
public interface EventClient {
  /**
   * Called when the Android-reported location changes.
   * 
   * {@link Location#getJson(StringBuffer)} can be called to obtain information
   * about the new location.
   */
  public void onLocation();
}
